:set nu
:set ai
:set cursorline
:set tabstop=4
:set shiftwidth=4
:set mouse=a
:set history=100
:inoremap ( ()<Esc>i
:inoremap " ""<Esc>i
:inoremap ' ''<Esc>i
:inoremap [ []<Esc>i
:inoremap {<CR> {<CR>}<Esc>ko
